### ISSUE TITLE
CB no longer compiles with the recent version of OCaml

### ISSUE THREAD

**Issue by DrShah-Quant** [ykazakov/cb-reasoner#3]
i am trying to compile the project however upon running make, it is giving the following error. 
```
descending to src
make[1]: Entering directory '/home/shah/Desktop/reasoners/cb-reasoner-master/src'
ocamlbuild -build-dir _build main/cb.native
+ ocamlopt.opt unix.cmxa -I /home/shah/.opam/default/lib/ocamlbuild /home/shah/.opam/default/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/shah/.opam/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 13, characters 11-64:
Error: Unbound module Ocamlbuild_pack.Ocamlbuild_Myocamlbuild_config
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
Makefile:8: recipe for target 'main' failed
make[1]: *** [main] Error 10
make[1]: Leaving directory '/home/shah/Desktop/reasoners/cb-reasoner-master/src'
Makefile:14: recipe for target 'src' failed
make: *** [src] Error 2
```
 It has problem when it runs myocamlbuild.ml file.. i guess there is some compability issues with the newer ocambuild. 

Here is the comments i got from ocamlbuild github

OCamlbuild exports a stable interface for plugin users as the Ocamlbuild_plugin module. Using Ocamlbuild_pack directly accesses ocamlbuild's internal definitions, and is recommended against as there are no guarantees of backward-compatibility.

In your specific case, a module is used by this code that indeed was removed in more recent ocamlbuild versions (its presence was an artifact of the specific way ocamlbuild's build system was integrated into the compiler distribution). I could correctly build this software with OCaml 3.12.1, 4.00.1 and 4.01.0, but not any more recent version of OCaml and ocamlbuild.

Using opam makes it easy to install old OCaml versions:

opam install 4.01.0
eval $(opam env --switch=4.01.0)
make # if in the project's directoyr

If you are interested in patching this software to make it compatible with more recent OCaml versions, we could discuss how to get the corresponding information in a more robust way.

In any case, I'm closing this as it is not a problem of ocamlbuild, but rather a maintenance question for cb-reasoner. (Of course, feel free to post further comments.)

**Comment by ykazakov** [comment]
@nathar, please reference the ocamlbuild issue, do not copy it here!

**Comment by ykazakov** [comment]
Does switching to the older version of OCaml resolve the issue?

**Comment by DrShah-Quant** [comment]
i can compile using version 4.01.0 however the "make install" does not work.. i am very new to OCaml.. i just tried to copy cb.native to bin folder and ./cb from bin folder it did not run.. it gave error "Fatal error: exception Sys_error("Illegal seek")".. did i do anything wrong... may be you can update your make file?

**Comment by ykazakov** [comment]
OK, great to hear that you can compile with 4.01.0!
"Make install" has nothing to do with OCaml. It just copies the produced file into bin. What exactly "does not work"?
Did you try ```./cb --help```? (Did you read README?)

**Comment by ykazakov** [comment]
I think the bin directory is missing that is why the file is not copied.

**Comment by DrShah-Quant** [comment]
1. In the make file the path info is wrong. It tries to copy cb.native from  ./src/cb.native however the compiler puts cb.native file inside ./src/_build/main/cb.native.
2. Yea ./cb --help works after i modified the make file. I initially wrongly used it that's why i got Sys_error("illegal seek)" error.
